main.py: fix tags filtering
scylladb/scylla-java-driver-matrix pull request #60
Opened 2024-12-09 23:21 UTC by fruch

code was picking bunch of tags which are not offical release

like the following
```
packaging.version.InvalidVersion: Invalid version: '4.2.x'
```

adding more things to filter out from the upstream tags, so we'll hit only offical releases

2024-12-09 23:23 UTC, fruch commented
test it locally, 
`4.18.0` seems to start running,  
but still a patch for `4.18.1` is broken (i.e. the patch from `4.18.0` doesn't apply)

2024-12-10 01:07 UTC, dkropachev requested changes

2024-12-10 01:07 UTC, dkropachev commented on main.py
> +    filter_version = f"| grep {'' if is_scylla_driver else '-v '}'.*\..*\..*\.' | grep -v '[-_x]'"
`-v` for scylla does not make any sense, let's fix it
```suggestion
    filter_version = "| grep -P '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'" if is_scylla_driver else "| grep -P '[0-9]+\.[0-9]+\.[0-9]+'"
```

2024-12-10 21:51 UTC, Bouncheck approved these changes
LGTM, ran it and it does in fact filter out weird versions.

2024-12-10 21:51 UTC, Bouncheck commented on main.py
> +    filter_version = f"| grep {'' if is_scylla_driver else '-v '}'.*\..*\..*\.' | grep -v '[-_x]'"
This suggestion will match for example datastax drivers with scylla versions because if they have 4 sections, then they have at least 3 sections too.

2024-12-11 13:34 UTC, dkropachev commented on main.py
> +    filter_version = f"| grep {'' if is_scylla_driver else '-v '}'.*\..*\..*\.' | grep -v '[-_x]'"
This is valid concern, but `scylla-pkg` runs datastax tests from datastax repo, so it won't break anything.
To address it you can wrap regexp into '^<regexp>$':
```suggestion
    filter_version = "| grep -P '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'" if is_scylla_driver else "| grep -P '^[0-9]+\.[0-9]+\.[0-9]+$'"
```

2024-12-11 14:57 UTC, fruch commented on main.py
> +    filter_version = f"| grep {'' if is_scylla_driver else '-v '}'.*\..*\..*\.' | grep -v '[-_x]'"
@dkropachev @Bouncheck feel free to take over the PR, and change.

I just noticed those weird versions, and it was annoying me

2024-12-11 15:01 UTC, dkropachev approved these changes

2024-12-11 15:01 UTC, merged